-- The Daddy's Cafe — shared website/admin/POS upgrade
-- Run once in Supabase SQL Editor, then add SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to Vercel Environment Variables.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Compatibility for projects that already had a categories table using `active`.
alter table public.categories add column if not exists sort_order integer not null default 0;
alter table public.categories add column if not exists is_active boolean not null default true;
do $$ begin
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='categories' and column_name='active') then
    execute 'update public.categories set is_active = coalesce(active, true)';
  end if;
end $$;

insert into public.categories(name,sort_order)
select category, row_number() over(order by category)
from (select distinct category from public.menu_items where category is not null and category <> '') q
on conflict(name) do nothing;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  phone text not null unique,
  name text,
  address text,
  landmark text,
  order_count integer not null default 0,
  total_spend numeric(12,2) not null default 0,
  last_order_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  customer_name text,
  customer_phone text,
  order_type text,
  delivery_address text,
  landmark text,
  schedule_text text,
  note text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  platform_fee numeric(12,2) not null default 0,
  handling_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method text,
  payment_status text,
  payment_id text,
  razorpay_order_id text,
  channel text not null default 'Website',
  order_status text not null default 'Paid',
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

-- Compatibility for projects that already had an older `orders` table.
alter table public.orders add column if not exists order_id text;
alter table public.orders add column if not exists invoice_number text;
alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists order_type text;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists landmark text;
alter table public.orders add column if not exists schedule_text text;
alter table public.orders add column if not exists note text;
alter table public.orders add column if not exists items jsonb not null default '[]'::jsonb;
alter table public.orders add column if not exists subtotal numeric(12,2) not null default 0;
alter table public.orders add column if not exists discount numeric(12,2) not null default 0;
alter table public.orders add column if not exists platform_fee numeric(12,2) not null default 0;
alter table public.orders add column if not exists handling_fee numeric(12,2) not null default 0;
alter table public.orders add column if not exists total numeric(12,2) not null default 0;
alter table public.orders add column if not exists payment_method text;
alter table public.orders add column if not exists payment_status text;
alter table public.orders add column if not exists payment_id text;
alter table public.orders add column if not exists razorpay_order_id text;
alter table public.orders add column if not exists channel text default 'Website';
alter table public.orders add column if not exists order_status text default 'Paid';
alter table public.orders add column if not exists created_at timestamptz not null default now();
alter table public.orders add column if not exists paid_at timestamptz;
create unique index if not exists orders_invoice_number_unique on public.orders(invoice_number) where invoice_number is not null;
create unique index if not exists orders_order_id_unique on public.orders(order_id) where order_id is not null;


alter table public.categories enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Public read active categories" on public.categories;
create policy "Public read active categories" on public.categories for select using (is_active = true or auth.uid() in (select user_id from public.admin_users));

drop policy if exists "Admins manage categories" on public.categories;
create policy "Admins manage categories" on public.categories for all using (auth.uid() in (select user_id from public.admin_users)) with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "Admins read customers" on public.customers;
create policy "Admins read customers" on public.customers for select using (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "Admins manage customers" on public.customers;
create policy "Admins manage customers" on public.customers for all using (auth.uid() in (select user_id from public.admin_users)) with check (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "Admins read orders" on public.orders;
create policy "Admins read orders" on public.orders for select using (auth.uid() in (select user_id from public.admin_users));

drop policy if exists "Admins manage orders" on public.orders;
create policy "Admins manage orders" on public.orders for all using (auth.uid() in (select user_id from public.admin_users)) with check (auth.uid() in (select user_id from public.admin_users));


-- Business hours / ordering availability
create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  ordering_enabled boolean not null default true,
  timezone text not null default 'Asia/Kolkata',
  business_hours jsonb not null default '{
    "monday":[["10:00","14:00"],["16:00","22:00"]],
    "tuesday":[["10:00","14:00"],["16:00","22:00"]],
    "wednesday":[["10:00","14:00"],["16:00","22:00"]],
    "thursday":[["10:00","14:00"],["16:00","22:00"]],
    "friday":[["10:00","14:00"],["16:00","22:00"]],
    "saturday":[["10:00","14:00"],["16:00","22:00"]],
    "sunday":[["17:30","22:00"]]
  }'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.store_settings(id) values (1)
on conflict(id) do nothing;

alter table public.store_settings enable row level security;

drop policy if exists "Public read store settings" on public.store_settings;
create policy "Public read store settings" on public.store_settings
for select using (true);

drop policy if exists "Admins manage store settings" on public.store_settings;
create policy "Admins manage store settings" on public.store_settings
for all
using (auth.uid() in (select user_id from public.admin_users))
with check (auth.uid() in (select user_id from public.admin_users));
